### ISSUE TITLE
cv2.pyd lacked

### ISSUE THREAD

**Issue by LeeRock** [cesardelgadof/OpenCVBinaries#2]
This binary Project is great.But I use Python in my work group.
Could you please offer the cv2.pyd for us？
Or write a blog to tell us the way to build all the file in Windows?
Thank you~Cesar Delgado Fernandez~

**Comment by ghost** [comment]
What is the python version you use ?
I have python 3.4

**Comment by LeeRock** [comment]
I hava Python 2.7.12 .The message displayed on python   is as follow：
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by ghost** [comment]
@LeeRock added python 2 support.

**Comment by LeeRock** [comment]
Thank You Very Much
